version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_FOLDER=${DATABASE_FOLDER}
    ports:
      - '5432:5432'
    volumes:
      - $DATABASE_FOLDER:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
